


export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description: "Get interview questions and model answers based on your role, experience, and specific focus areas - no"
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description: "Expand answers only when your are ready. Dive deeper into any concept instantly with AI-powered detailed explainations. "
    },
    {
        id: "03",
        title: "Capture Your Insights",
        description: "Add personal notes to any question and pin important ones to the top - making your learning more organized and effective."
    },
    {
        id: "04",
        title: "Understand to 'Why' Behind Answers ",
        description: "Beyond just answers, unlock detailed concept explainations generated by AI, helping you truly master subjects that matter, not just memorize answers."
    },
    {
        id: "05",
        title: "Save, Organize and Revisit",
        description: "Easily save your interview sets, organize them neatly in your dashboard, and pickup your preparation right where you left off."
    },

];